import { IProduct } from "@shared/components/types";
import colaPavoImg from "@img/card/cola-pavo.png" 
import melenaImg from "@img/card/melena-leon.png" 
import reishiImg from "@img/card/reishi.png" 
import cordycepsImg from "@img/card/cordyceps-militaris.png"
import colaPavoThumb from "@img/card/thumbnail-cola-pavo.png" 
import melenaThumb from "@img/card/thumbnail-melena-leon.png" 
import reishiThumb from "@img/card/thumbnail-reishi.png" 
import cordycepsThumb from "@img/card/thumbnail-cordyceps-militaris.png" 

export const catalogue: IProduct[] = [{
  id: 111,
  sectionId: 1,
  title: 'Melena de León - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Ayuda a tu cerebro y mejora tu salud gastrointestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: melenaImg,
  urlThumbnail: melenaThumb,
  isValid: true,
},
{
  id: 112,
  sectionId: 1,
  title: 'Cordyceps Militaris - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Vigorizante, reduce la fatiga y estimula el sistema inmunológico.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: cordycepsImg,
  urlThumbnail: cordycepsThumb,
  isValid: true,
},
{
  id: 113,
  sectionId: 1,
  title: 'Reishi - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Lucha contra el cáncer, mejora respuesta inmune y efecto antioxidante.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: reishiImg,
  urlThumbnail: reishiThumb,
  isValid: true,
},
{
  id: 115,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: colaPavoImg,
  urlThumbnail: colaPavoThumb,
  isValid: true,
},
{
  id: 116,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  isValid: true,
},
{
  id: 117,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  isValid: true,
},
{
  id: 118,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  isValid: true,
},
{
  id: 119,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  isValid: true,
},
{
  id: 120,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  isValid: true,
},
]